title: Hesam Damghanian
plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: solarized-dark
  social_links:
    twitter: c3nt4ur1
    github:  Sk7w4tch3r

highlighter: rouge
kramdown:
    math_engine: katex
    syntax_highlighter: rouge
